FROM node:20-alpine

WORKDIR /app

RUN corepack enable

COPY packages/dashboard/package.json packages/dashboard/pnpm-lock.yaml ./
RUN pnpm install --prod

COPY packages/dashboard ./packages/dashboard

WORKDIR /app/packages/dashboard

RUN pnpm run build

EXPOSE 3000

CMD ["pnpm", "start"]