# -------------------- POSTGRES --------------------
services:
  postgres:
    image: postgres:17
    container_name: fakegaming-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-fakegaming}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fakegaming}
      POSTGRES_DB: ${POSTGRES_DB:-fakegaming}
    # Internal only by default; uncomment to expose externally for testing
    # ports:
    #   - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ${POSTGRES_DATA_PATH:-./data/postgres}:/var/lib/postgresql/data

  # -------------------- BOT --------------------
  bot:
    image: zeffuro/fakegaming-bot:latest
    container_name: fakegaming-bot
    restart: unless-stopped
    env_file:
      - ./packages/bot/.env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://${POSTGRES_USER:-fakegaming}:${POSTGRES_PASSWORD:-fakegaming}@fakegaming-postgres:5432/${POSTGRES_DB:-fakegaming}}
      # Health server (internal by default)
      BOT_HEALTH_HOST: ${BOT_HEALTH_HOST:-127.0.0.1}
      BOT_HEALTH_PORT: ${BOT_HEALTH_PORT:-8081}
    volumes:
      - ${BOT_DATA_PATH:-./data/bot}:/app/data
    depends_on:
      - postgres
    # Expose bot health port only if needed
    # ports:
    #   - "${BOT_HEALTH_PORT:-8081}:${BOT_HEALTH_PORT:-8081}"

  # -------------------- API --------------------
  api:
    image: zeffuro/fakegaming-api:latest
    container_name: fakegaming-api
    restart: unless-stopped
    env_file:
      - ./packages/api/.env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://${POSTGRES_USER:-fakegaming}:${POSTGRES_PASSWORD:-fakegaming}@fakegaming-postgres:5432/${POSTGRES_DB:-fakegaming}}
    depends_on:
      - postgres
    # Expose API port only if needed
    # ports:
    #   - "${PORT:-3001}:${PORT:-3001}"

  # -------------------- DASHBOARD --------------------
  dashboard:
    image: zeffuro/fakegaming-dashboard:latest
    container_name: fakegaming-dashboard
    restart: unless-stopped
    env_file:
      - ./packages/dashboard/.env
    depends_on:
      - api
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
