packages:
  - packages/*
  - scripts

overrides:
  postcss: '8.5.15'
  protobufjs: '8.6.1'
  'sequelize>uuid': '11.1.1'
  'twisted>uuid': '11.1.1'
  vite: '8.0.16'

allowBuilds:
  '@scarf/scarf': true
  '@swc/core': true
  canvas: true
  esbuild: true
  protobufjs: true
  sharp: true
  sqlite3: true
  unrs-resolver: true
