import type { SupportedOutputLocale } from '@zeffuro/fakegaming-common';

export const API_COPY_EN = {
    validationBody: 'Body validation failed',
    validationQuery: 'Query validation failed',
    validationParams: 'Params validation failed',
    validationRequired: 'Required',
    validationInvalid: 'Invalid value',
    validationString: 'Expected text',
    validationNumber: 'Expected a number',
    validationBoolean: 'Expected true or false',
    validationArray: 'Expected a list',
    validationTooSmall: 'Value is too small',
    validationTooBig: 'Value is too large',
    validationFormat: 'Invalid format',
    validationExpectedTime: 'Expected time in HH:mm',
    validationAnimeIdentifier: 'anilistId or title is required',
    validationCalendarDate: 'Invalid calendar date',
    validationOneField: 'At least one field must be provided',
    validationDateTime: 'Invalid date-time',
    validationRecurrenceTimezone: 'recurrenceTimezone is required when recurrence is set',
    validationNoteContent: 'title or body is required',
    validationIdentifierRequired: 'identifier is required',
    validationUsernameRequired: 'username is required',
    unauthorized: 'Unauthorized',
    authenticationRequired: 'Authentication required',
    forbidden: 'Forbidden',
    guildForbidden: 'Not authorized for this server',
    adminOnly: 'Only dashboard admins can access this resource',
    notFound: 'Not found',
    badRequest: 'Bad request',
    duplicateEntry: 'Duplicate entry',
    unexpectedError: 'Unexpected error',
    rateLimit: 'Rate limit exceeded',
    tooManyRequests: 'Too many requests',
    csrf: 'The security token is missing or invalid',
    missingGuildId: 'Missing server ID parameter',
    authorizationCheckFailed: 'Internal server error during authorization check',
    guildAccessCacheUnavailable: 'Server access could not be verified because the access cache is unavailable. Refresh the dashboard session and try again.',
    guildAccessExpired: 'Server access could not be verified because cached Discord servers expired. Refresh the dashboard session and try again.',
    guildAccessRefreshFailed: 'Server access could not be refreshed from Discord. Refresh the dashboard session and try again.',
    guildAccessUnavailable: 'Server access could not be verified. Refresh the dashboard session and try again.',
    guildAccessRecovery: 'Refresh the dashboard session, then retry the request.',
    permissionSnapshotNotFound: 'Permission snapshot was not found.',
    permissionReadUnavailable: 'Discord role or channel permissions could not be read right now.',
    noteNotFound: 'Note not found',
    reminderNotFound: 'Reminder not found',
    reminderInvalidTimespan: 'Invalid timespan. Use values like 10m, 1h, or 2d.',
    reminderInvalidRecurrence: 'Invalid recurrence. Use values like daily, weekly, monthly, every 2 weeks, or 3mo with a valid timezone.',
    reminderRecurringOnly: 'Only recurring reminders can be paused.',
    reminderExists: 'Reminder with this ID already exists',
    digestInvalidSchedule: 'Invalid digest schedule or timezone.',
    digestNotFound: 'Digest subscription not found',
    quoteNotFound: 'Quote not found',
    quoteApprovedOnly: 'Only approved quotes can be rendered as cards',
    quoteExists: 'Quote with this ID already exists',
    disabledCommandNotFound: 'Disabled command not found',
    disabledModuleNotFound: 'Disabled module not found',
    serverNotFound: 'Server not found',
    userNotFound: 'User not found',
    birthdayNotFound: 'Birthday not found',
    birthdayExists: 'Birthday already exists for this user in this guild',
    invalidDiscordOAuthCode: 'Invalid Discord OAuth code',
    discordAuthenticationFailed: 'Failed to authenticate with Discord',
    animeSubscriptionForbidden: 'Not authorized for this anime subscription',
    animeNotFound: 'Anime not found',
    animeNotSubscribable: '{title} is {status}.',
    animeNotSubscribableStatus: 'not subscribable',
    integrationProviderConfigRequired: 'Provider and config ID are required',
    integrationHealthNotFound: 'Integration health record not found',
    unknownJobName: 'Unknown job name: {name}',
    jobsUnavailable: 'Jobs are not enabled or queue is not initialized',
    patchRecordsSameGame: 'Patch records must be from the same game',
    patchNoteNotFound: 'Patch note not found',
    patchSubscriptionNotFound: 'Patch subscription not found',
    blueskyHandleRequired: 'blueskyHandle is required',
    twitchConfigNotFound: 'Twitch stream config not found',
    youtubeVideoConfigNotFound: 'YouTube video config not found',
    riotLinkNotFound: 'Riot link not found',
    riotTagRequired: 'Riot ID must include a tag line for Account-V1 validation.',
    riotIdRequired: 'Riot ID must include a game name and tag line.',
    riotRegionUnsupported: 'Unsupported Riot region: {region}',
    riotApiKeyMissing: 'Riot Account API key is not configured.',
    riotValidationRequestFailed: 'Riot Account API validation request failed.',
    riotAccountNotFound: 'Riot ID could not be verified through Account-V1.',
    riotValidationFailed: 'Riot Account API validation failed.',
    riotInvalidPayload: 'Riot Account API returned an invalid account payload.',
    riotPuuidMismatch: 'PUUID does not match the Riot ID returned by Account-V1.',
    steamMultipleMatches: 'Multiple Steam apps matched this input. Choose one of the suggested results.',
    steamAppNotFound: 'Steam app not found',
    steamNewsSubscriptionNotFound: 'Steam news subscription not found',
    setupTemplateNotFound: 'Setup template not found',
    tiktokConfigNotFound: 'TikTok stream config not found',
    tiktokSessionAttached: 'TikTok cookie material is configured, but this connector path does not expose expiry age and is not attaching cookies to live checks.',
    tiktokSessionUnrecognized: 'TikTok cookie material is configured, but no likely session cookie was detected and this connector path is not attaching cookies to live checks.',
    tiktokSessionMissing: 'No TikTok cookie material is configured for this process.',
    tiktokViewers: 'Viewers',
    tiktokUptime: 'Uptime',
    tiktokDefaultContent: 'Hey @everyone, {username} is now live! {url}',
    tiktokWatchStream: 'Watch Stream',
    blueskyLikes: 'Likes',
    blueskyReposts: 'Reposts',
    blueskyReplies: 'Replies',
    blueskyDefaultContent: 'Hey @everyone, new Bluesky post from {author}: {url}',
    blueskyViewPost: 'View Post',
    blueskyConfigNotFound: 'Bluesky post config not found',
    youtubeDuration: 'Duration',
    youtubeViews: 'Views',
    youtubeDefaultContent: 'Hey @everyone, new video from {author}: {url}',
    youtubeWatchVideo: 'Watch Video',
    birthday: 'Happy birthday <@{userId}>{age}!',
    birthdayAge: ' (turning {age})',
    reminder: 'Reminder: {message}\n(set {elapsed})',
    animeTitle: '{title} episode {episode}',
    animeDescription: 'Episode {episode} airs <t:{airingAt}:R>.',
    animeAuthor: 'Anime reminder',
    animeCalendarName: 'Fakegaming Anime Reminders',
    animeCalendarEpisode: '{title} Episode {episode}',
    animeCalendarReminder: 'Reminder {minutes} minutes before airing',
    calendarNotFound: 'Calendar not found',
    quoteOfDay: 'Quote of the day ({dateKey})',
    blueskyTitle: '{author} posted on Bluesky',
    blueskyFallback: 'New post on Bluesky',
    twitchLiveTitle: '{streamer} is now live!',
    twitchLiveFallback: 'Live on Twitch!',
    twitchViewers: 'Viewers',
    twitchGame: 'Game',
    twitchUptime: 'Uptime',
    twitchNotAvailable: 'N/A',
    twitchDefaultContent: 'Hey @everyone, {streamer} is now live! {url}',
    twitchWatchStream: 'Watch Stream',
    twitchVodTitle: 'Latest VOD from {streamer}',
    twitchVodDescription: 'Latest Twitch archive from {streamer}.',
    twitchVodDuration: 'Duration',
    twitchVodViews: 'Views',
    twitchVodDefaultContent: 'Latest VOD from {streamer}: {url}',
    twitchWatchVod: 'Watch VOD',
    tiktokLiveTitle: '{username} is now live on TikTok!',
    tiktokLiveFallback: 'Live on TikTok!',
    steamNewsFooter: 'Steam News',
    steamAppFallback: 'Steam app {appId}',
    steamNewsEmptyDescription: 'New Steam announcement published.',
    youtubeUnknownAuthor: 'Unknown',
    digestTitle: 'Your {frequency} digest',
    digestEmpty: 'Nothing new for this digest.',
    digestReminders: 'Reminders',
    digestAnime: 'Anime',
    digestDailyReminderTitle: 'Daily reminder digest',
    digestWeeklyReminderTitle: 'Weekly reminder digest',
    digestDailyPersonalTitle: 'Daily personal digest',
    digestWeeklyPersonalTitle: 'Weekly personal digest',
    digestUpcomingReminders: 'Upcoming reminders through <t:{windowEndsAt}:f>.',
    digestUpcomingItems: 'Upcoming items through <t:{windowEndsAt}:f>.',
    digestMore: '...and {count} more.',
    digestAnimeReminders: 'Anime reminders',
    digestEpisode: ' episode {episode}',
    digestAirs: ' airs <t:{airingAt}:R>.',
} as const;

export type ApiCopyKey = keyof typeof API_COPY_EN;

export const API_COPY_NL = {
    validationBody: 'Validatie van de inhoud is mislukt',
    validationQuery: 'Validatie van de query is mislukt',
    validationParams: 'Validatie van de parameters is mislukt',
    validationRequired: 'Verplicht',
    validationInvalid: 'Ongeldige waarde',
    validationString: 'Tekst verwacht',
    validationNumber: 'Een getal verwacht',
    validationBoolean: 'Waar of onwaar verwacht',
    validationArray: 'Een lijst verwacht',
    validationTooSmall: 'De waarde is te klein',
    validationTooBig: 'De waarde is te groot',
    validationFormat: 'Ongeldige notatie',
    validationExpectedTime: 'Gebruik een tijd in de notatie UU:mm',
    validationAnimeIdentifier: 'anilistId of title is verplicht',
    validationCalendarDate: 'Ongeldige kalenderdatum',
    validationOneField: 'Geef ten minste één veld op',
    validationDateTime: 'Ongeldige datum of tijd',
    validationRecurrenceTimezone: 'recurrenceTimezone is verplicht wanneer recurrence is ingesteld',
    validationNoteContent: 'title of body is verplicht',
    validationIdentifierRequired: 'identifier is verplicht',
    validationUsernameRequired: 'username is verplicht',
    unauthorized: 'Niet geautoriseerd',
    authenticationRequired: 'Je moet ingelogd zijn',
    forbidden: 'Geen toegang',
    guildForbidden: 'Je hebt geen toegang tot deze server',
    adminOnly: 'Alleen dashboardbeheerders hebben toegang tot dit onderdeel',
    notFound: 'Niet gevonden',
    badRequest: 'Ongeldig verzoek',
    duplicateEntry: 'Dit item bestaat al',
    unexpectedError: 'Onverwachte fout',
    rateLimit: 'Je hebt te veel verzoeken verstuurd',
    tooManyRequests: 'Te veel verzoeken',
    csrf: 'De beveiligingstoken ontbreekt of is ongeldig',
    missingGuildId: 'De server-ID ontbreekt',
    authorizationCheckFailed: 'Interne serverfout tijdens de toegangscontrole',
    guildAccessCacheUnavailable: 'Je servertoegang kon niet worden gecontroleerd omdat de toegangscache niet beschikbaar is. Vernieuw je dashboardsessie en probeer het opnieuw.',
    guildAccessExpired: 'Je servertoegang kon niet worden gecontroleerd omdat de opgeslagen Discord-servers zijn verlopen. Vernieuw je dashboardsessie en probeer het opnieuw.',
    guildAccessRefreshFailed: 'Je servertoegang kon niet bij Discord worden vernieuwd. Vernieuw je dashboardsessie en probeer het opnieuw.',
    guildAccessUnavailable: 'Je servertoegang kon niet worden gecontroleerd. Vernieuw je dashboardsessie en probeer het opnieuw.',
    guildAccessRecovery: 'Vernieuw je dashboardsessie en probeer het verzoek opnieuw.',
    permissionSnapshotNotFound: 'De momentopname van de rechten is niet gevonden.',
    permissionReadUnavailable: 'De rollen of kanaalrechten van Discord kunnen nu niet worden gelezen.',
    noteNotFound: 'Notitie niet gevonden',
    reminderNotFound: 'Herinnering niet gevonden',
    reminderInvalidTimespan: 'Ongeldige tijdsduur. Gebruik bijvoorbeeld 10m, 1h of 2d.',
    reminderInvalidRecurrence: 'Ongeldige herhaling. Gebruik bijvoorbeeld daily, weekly, monthly, every 2 weeks of 3mo met een geldige tijdzone.',
    reminderRecurringOnly: 'Alleen terugkerende herinneringen kunnen worden gepauzeerd.',
    reminderExists: 'Er bestaat al een herinnering met deze ID',
    digestInvalidSchedule: 'Ongeldig schema of ongeldige tijdzone voor het overzicht.',
    digestNotFound: 'Abonnement op het overzicht niet gevonden',
    quoteNotFound: 'Citaat niet gevonden',
    quoteApprovedOnly: 'Alleen goedgekeurde citaten kunnen als kaart worden weergegeven',
    quoteExists: 'Er bestaat al een citaat met deze ID',
    disabledCommandNotFound: 'Uitgeschakelde opdracht niet gevonden',
    disabledModuleNotFound: 'Uitgeschakelde module niet gevonden',
    serverNotFound: 'Server niet gevonden',
    userNotFound: 'Gebruiker niet gevonden',
    birthdayNotFound: 'Verjaardag niet gevonden',
    birthdayExists: 'Voor deze gebruiker bestaat al een verjaardag in deze server',
    invalidDiscordOAuthCode: 'Ongeldige Discord OAuth-code',
    discordAuthenticationFailed: 'Authenticatie met Discord is mislukt',
    animeSubscriptionForbidden: 'Je hebt geen toegang tot dit anime-abonnement',
    animeNotFound: 'Anime niet gevonden',
    animeNotSubscribable: 'Je kunt {title} niet volgen (status: {status}).',
    animeNotSubscribableStatus: 'niet beschikbaar',
    integrationProviderConfigRequired: 'Provider en configuratie-ID zijn verplicht',
    integrationHealthNotFound: 'Integratiestatus niet gevonden',
    unknownJobName: 'Onbekende taaknaam: {name}',
    jobsUnavailable: 'Taken zijn niet ingeschakeld of de wachtrij is niet geïnitialiseerd',
    patchRecordsSameGame: 'Patchrecords moeten van dezelfde game zijn',
    patchNoteNotFound: 'Patchnotitie niet gevonden',
    patchSubscriptionNotFound: 'Abonnement op patchnotities niet gevonden',
    blueskyHandleRequired: 'blueskyHandle is verplicht',
    twitchConfigNotFound: 'Twitch-streamconfiguratie niet gevonden',
    youtubeVideoConfigNotFound: 'YouTube-videoconfiguratie niet gevonden',
    riotLinkNotFound: 'Riot-koppeling niet gevonden',
    riotTagRequired: 'De Riot ID moet een tagline bevatten voor Account-V1-validatie.',
    riotIdRequired: 'De Riot ID moet een gamenaam en tagline bevatten.',
    riotRegionUnsupported: 'Niet-ondersteunde Riot-regio: {region}',
    riotApiKeyMissing: 'De API-sleutel voor Riot Account is niet ingesteld.',
    riotValidationRequestFailed: 'Het validatieverzoek aan de Riot Account API is mislukt.',
    riotAccountNotFound: 'De Riot ID kon niet via Account-V1 worden geverifieerd.',
    riotValidationFailed: 'Validatie via de Riot Account API is mislukt.',
    riotInvalidPayload: 'De Riot Account API gaf ongeldige accountgegevens terug.',
    riotPuuidMismatch: 'De PUUID komt niet overeen met de Riot ID van Account-V1.',
    steamMultipleMatches: 'Meerdere Steam-apps komen overeen. Kies een van de voorgestelde resultaten.',
    steamAppNotFound: 'Steam-app niet gevonden',
    steamNewsSubscriptionNotFound: 'Abonnement op Steam-nieuws niet gevonden',
    setupTemplateNotFound: 'Instellingensjabloon niet gevonden',
    tiktokConfigNotFound: 'TikTok-streamconfiguratie niet gevonden',
    tiktokSessionAttached: 'TikTok-cookiemateriaal is ingesteld, maar dit connectorpad toont geen verloopdatum en voegt geen cookies toe aan livestreamcontroles.',
    tiktokSessionUnrecognized: 'TikTok-cookiemateriaal is ingesteld, maar er is geen waarschijnlijke sessiecookie gevonden en dit connectorpad voegt geen cookies toe aan livestreamcontroles.',
    tiktokSessionMissing: 'Er is voor dit proces geen TikTok-cookiemateriaal ingesteld.',
    tiktokViewers: 'Kijkers',
    tiktokUptime: 'Livestreamduur',
    tiktokDefaultContent: 'Hallo @everyone, {username} is nu live! {url}',
    tiktokWatchStream: 'Livestream bekijken',
    blueskyLikes: 'Vind-ik-leuks',
    blueskyReposts: 'Reposts',
    blueskyReplies: 'Reacties',
    blueskyDefaultContent: 'Hallo @everyone, nieuw Bluesky-bericht van {author}: {url}',
    blueskyViewPost: 'Bericht bekijken',
    blueskyConfigNotFound: 'Bluesky-berichtconfiguratie niet gevonden',
    youtubeDuration: 'Duur',
    youtubeViews: 'Weergaven',
    youtubeDefaultContent: 'Hallo @everyone, nieuwe video van {author}: {url}',
    youtubeWatchVideo: 'Video bekijken',
    birthday: 'Gefeliciteerd met je verjaardag <@{userId}>{age}!',
    birthdayAge: ' (je wordt {age})',
    reminder: 'Herinnering: {message}\n(ingesteld {elapsed})',
    animeTitle: '{title} aflevering {episode}',
    animeDescription: 'Aflevering {episode} wordt <t:{airingAt}:R> uitgezonden.',
    animeAuthor: 'Animeherinnering',
    animeCalendarName: 'Fakegaming-animeherinneringen',
    animeCalendarEpisode: '{title} Aflevering {episode}',
    animeCalendarReminder: 'Herinnering {minutes} minuten voor uitzending',
    calendarNotFound: 'Kalender niet gevonden',
    quoteOfDay: 'Citaat van de dag ({dateKey})',
    blueskyTitle: '{author} heeft iets op Bluesky geplaatst',
    blueskyFallback: 'Nieuw bericht op Bluesky',
    twitchLiveTitle: '{streamer} is nu live!',
    twitchLiveFallback: 'Live op Twitch!',
    twitchViewers: 'Kijkers',
    twitchGame: 'Game',
    twitchUptime: 'Livestreamduur',
    twitchNotAvailable: 'n.v.t.',
    twitchDefaultContent: 'Hallo @everyone, {streamer} is nu live! {url}',
    twitchWatchStream: 'Livestream bekijken',
    twitchVodTitle: 'Nieuwste VOD van {streamer}',
    twitchVodDescription: 'Nieuwste Twitch-opname van {streamer}.',
    twitchVodDuration: 'Duur',
    twitchVodViews: 'Weergaven',
    twitchVodDefaultContent: 'Nieuwste VOD van {streamer}: {url}',
    twitchWatchVod: 'VOD bekijken',
    tiktokLiveTitle: '{username} is nu live op TikTok!',
    tiktokLiveFallback: 'Live op TikTok!',
    steamNewsFooter: 'Steam-nieuws',
    steamAppFallback: 'Steam-app {appId}',
    steamNewsEmptyDescription: 'Er is een nieuwe Steam-aankondiging gepubliceerd.',
    youtubeUnknownAuthor: 'Onbekend',
    digestTitle: 'Jouw {frequency} overzicht',
    digestEmpty: 'Er is niets nieuws voor dit overzicht.',
    digestReminders: 'Herinneringen',
    digestAnime: 'Anime',
    digestDailyReminderTitle: 'Dagelijks herinneringenoverzicht',
    digestWeeklyReminderTitle: 'Wekelijks herinneringenoverzicht',
    digestDailyPersonalTitle: 'Dagelijks persoonlijk overzicht',
    digestWeeklyPersonalTitle: 'Wekelijks persoonlijk overzicht',
    digestUpcomingReminders: 'Aankomende herinneringen tot <t:{windowEndsAt}:f>.',
    digestUpcomingItems: 'Aankomende items tot <t:{windowEndsAt}:f>.',
    digestMore: '...en nog {count}.',
    digestAnimeReminders: 'Animeherinneringen',
    digestEpisode: ' aflevering {episode}',
    digestAirs: ' wordt <t:{airingAt}:R> uitgezonden.',
} as const satisfies Record<ApiCopyKey, string>;

export const API_COPY: Readonly<Record<SupportedOutputLocale, Readonly<Record<ApiCopyKey, string>>>> = {
    en: API_COPY_EN,
    nl: API_COPY_NL,
};
