import { resolveLocaleValue, type OutputLocaleValues } from '@zeffuro/fakegaming-common';
import type { SupportedOutputLocale } from '../../../core/localization.js';

const EN = {
    unknown: 'Unknown',
    noDescription: 'No description available.',
    unknownAnime: 'Unknown anime',
    status: 'Status',
    format: 'Format',
    origin: 'Origin',
    chapters: 'Chapters',
    volumes: 'Volumes',
    rating: 'Rating',
    popularity: 'Popularity',
    genres: 'Genres',
    rankings: 'Rankings',
    episodes: 'Episodes',
    nextEpisode: 'Next Episode',
    noUpcomingEpisode: 'No upcoming episode known.',
    native: 'Native',
    synonyms: 'Synonyms',
    animeSubscriptions: 'Anime subscriptions',
    noSubscriptions: 'No anime subscriptions yet.',
    paused: 'paused',
    next: 'next',
    reminder: 'min reminder',
    page: 'Page',
    subscription: 'subscription',
    subscriptions: 'subscriptions',
    upcomingEpisodes: 'Upcoming anime episodes',
    noUpcomingSubscriptions: 'No upcoming episodes found for your subscriptions.',
    anime: 'Anime',
    manga: 'Manga',
    search: 'search',
    unknownYear: 'unknown year',
    users: 'users',
    episodeShort: 'ep',
    episodesShort: 'eps',
    romaji: 'Romaji',
    exactOrSubscribe: 'Use autocomplete for exact selection, or a Subscribe button for DM reminders.',
    exactSelection: 'Use autocomplete for exact selection.',
    unscored: 'unscored',
    season: 'Anime season',
    noSeasonAnime: 'No anime found for that season.',
    titles: 'titles',
    moreResults: 'more results available',
    subscribe: 'Subscribe',
    unsubscribe: 'Unsubscribe',
    previous: 'Previous',
    nextButton: 'Next',
    never: 'Never',
    latestHealth: 'Latest health',
    lastChecked: 'Last checked',
    lastSuccess: 'Last success',
    lastFailure: 'Last failure',
    lastDelivery: 'Last delivery',
    consecutiveFailures: 'Consecutive failures',
    lastError: 'Last error',
    unknownError: 'Unknown error',
} as const;

export type AnimeCopy = { readonly [Key in keyof typeof EN]: string };

const NL: AnimeCopy = {
    unknown: 'Onbekend',
    noDescription: 'Geen beschrijving beschikbaar.',
    unknownAnime: 'Onbekende anime',
    status: 'Status',
    format: 'Indeling',
    origin: 'Herkomst',
    chapters: 'Hoofdstukken',
    volumes: 'Delen',
    rating: 'Beoordeling',
    popularity: 'Populariteit',
    genres: 'Genres',
    rankings: 'Ranglijsten',
    episodes: 'Afleveringen',
    nextEpisode: 'Volgende aflevering',
    noUpcomingEpisode: 'Geen komende aflevering bekend.',
    native: 'Oorspronkelijke titel',
    synonyms: 'Alternatieve titels',
    animeSubscriptions: 'Anime-abonnementen',
    noSubscriptions: 'Je hebt nog geen anime-abonnementen.',
    paused: 'gepauzeerd',
    next: 'volgende',
    reminder: 'min. vooraf melden',
    page: 'Pagina',
    subscription: 'abonnement',
    subscriptions: 'abonnementen',
    upcomingEpisodes: 'Komende anime-afleveringen',
    noUpcomingSubscriptions: 'Geen komende afleveringen gevonden voor je abonnementen.',
    anime: 'Anime',
    manga: 'Manga',
    search: 'zoeken',
    unknownYear: 'onbekend jaar',
    users: 'gebruikers',
    episodeShort: 'afl.',
    episodesShort: 'afl.',
    romaji: 'Romaji',
    exactOrSubscribe: 'Gebruik automatisch aanvullen voor een exacte keuze, of Abonneren voor meldingen via DM.',
    exactSelection: 'Gebruik automatisch aanvullen voor een exacte keuze.',
    unscored: 'niet beoordeeld',
    season: 'Animeseizoen',
    noSeasonAnime: 'Geen anime gevonden voor dat seizoen.',
    titles: 'titels',
    moreResults: 'meer resultaten beschikbaar',
    subscribe: 'Abonneren',
    unsubscribe: 'Opzeggen',
    previous: 'Vorige',
    nextButton: 'Volgende',
    never: 'Nooit',
    latestHealth: 'Laatste status',
    lastChecked: 'Laatst gecontroleerd',
    lastSuccess: 'Laatste succes',
    lastFailure: 'Laatste fout',
    lastDelivery: 'Laatst afgeleverd',
    consecutiveFailures: 'Opeenvolgende fouten',
    lastError: 'Laatste foutmelding',
    unknownError: 'Onbekende fout',
};

export function getAnimeCopy(locale: SupportedOutputLocale): AnimeCopy {
    return resolveLocaleValue(locale, { en: EN, nl: NL } satisfies OutputLocaleValues<AnimeCopy>);
}
