import type { paths } from "@/types/api";

// ----- Autogenerated endpoint type aliases -----

/**
 * Response for [POST /auth/login 200]
 *
 * @see paths["/auth/login"]["post"]["responses"]["200"]["content"]["application/json"]
 */
export type auth_login_post_Response200 = paths["/auth/login"]["post"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [POST /auth/login]
 *
 * @see paths["/auth/login"]["post"]["requestBody"]["content"]["application/json"]
 */
export type auth_login_post_Request = paths["/auth/login"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /birthdays 200]
 *
 * @see paths["/birthdays"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type birthdays_get_Response200 = paths["/birthdays"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [POST /birthdays]
 *
 * @see paths["/birthdays"]["post"]["requestBody"]["content"]["application/json"]
 */
export type birthdays_post_Request = paths["/birthdays"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /birthdays/{userId}/{guildId} 200]
 *
 * @see paths["/birthdays/{userId}/{guildId}"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type birthdays_userId_guildId_get_Response200 = paths["/birthdays/{userId}/{guildId}"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /disabledCommands 200]
 *
 * @see paths["/disabledCommands"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type disabledCommands_get_Response200 = paths["/disabledCommands"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [POST /disabledCommands]
 *
 * @see paths["/disabledCommands"]["post"]["requestBody"]["content"]["application/json"]
 */
export type disabledCommands_post_Request = paths["/disabledCommands"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /disabledCommands/check 200]
 *
 * @see paths["/disabledCommands/check"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type disabledCommands_check_get_Response200 = paths["/disabledCommands/check"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /disabledCommands/guild/{guildId} 200]
 *
 * @see paths["/disabledCommands/guild/{guildId}"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type disabledCommands_guild_guildId_get_Response200 = paths["/disabledCommands/guild/{guildId}"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /patchNotes 200]
 *
 * @see paths["/patchNotes"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type patchNotes_get_Response200 = paths["/patchNotes"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [POST /patchNotes]
 *
 * @see paths["/patchNotes"]["post"]["requestBody"]["content"]["application/json"]
 */
export type patchNotes_post_Request = paths["/patchNotes"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /patchNotes/{game} 200]
 *
 * @see paths["/patchNotes/{game}"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type patchNotes_game_get_Response200 = paths["/patchNotes/{game}"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /patchSubscriptions 200]
 *
 * @see paths["/patchSubscriptions"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type patchSubscriptions_get_Response200 = paths["/patchSubscriptions"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [POST /patchSubscriptions]
 *
 * @see paths["/patchSubscriptions"]["post"]["requestBody"]["content"]["application/json"]
 */
export type patchSubscriptions_post_Request = paths["/patchSubscriptions"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Request body for [PUT /patchSubscriptions]
 *
 * @see paths["/patchSubscriptions"]["put"]["requestBody"]["content"]["application/json"]
 */
export type patchSubscriptions_put_Request = paths["/patchSubscriptions"]["put"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /quotes 200]
 *
 * @see paths["/quotes"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type quotes_get_Response200 = paths["/quotes"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [POST /quotes]
 *
 * @see paths["/quotes"]["post"]["requestBody"]["content"]["application/json"]
 */
export type quotes_post_Request = paths["/quotes"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /quotes/search 200]
 *
 * @see paths["/quotes/search"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type quotes_search_get_Response200 = paths["/quotes/search"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /quotes/guild/{guildId} 200]
 *
 * @see paths["/quotes/guild/{guildId}"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type quotes_guild_guildId_get_Response200 = paths["/quotes/guild/{guildId}"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /quotes/guild/{guildId}/author/{authorId} 200]
 *
 * @see paths["/quotes/guild/{guildId}/author/{authorId}"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type quotes_guild_guildId_author_authorId_get_Response200 = paths["/quotes/guild/{guildId}/author/{authorId}"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /quotes/{id} 200]
 *
 * @see paths["/quotes/{id}"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type quotes_id_get_Response200 = paths["/quotes/{id}"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /reminders 200]
 *
 * @see paths["/reminders"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type reminders_get_Response200 = paths["/reminders"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [POST /reminders]
 *
 * @see paths["/reminders"]["post"]["requestBody"]["content"]["application/json"]
 */
export type reminders_post_Request = paths["/reminders"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /reminders/{id} 200]
 *
 * @see paths["/reminders/{id}"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type reminders_id_get_Response200 = paths["/reminders/{id}"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /servers 200]
 *
 * @see paths["/servers"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type servers_get_Response200 = paths["/servers"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /servers/{serverId} 200]
 *
 * @see paths["/servers/{serverId}"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type servers_serverId_get_Response200 = paths["/servers/{serverId}"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /twitch 200]
 *
 * @see paths["/twitch"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type twitch_get_Response200 = paths["/twitch"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [POST /twitch]
 *
 * @see paths["/twitch"]["post"]["requestBody"]["content"]["application/json"]
 */
export type twitch_post_Request = paths["/twitch"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /twitch/{id} 200]
 *
 * @see paths["/twitch/{id}"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type twitch_id_get_Response200 = paths["/twitch/{id}"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /users 200]
 *
 * @see paths["/users"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type users_get_Response200 = paths["/users"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [POST /users]
 *
 * @see paths["/users"]["post"]["requestBody"]["content"]["application/json"]
 */
export type users_post_Request = paths["/users"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /users/{discordId} 200]
 *
 * @see paths["/users/{discordId}"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type users_discordId_get_Response200 = paths["/users/{discordId}"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [PUT /users/{discordId}/timezone]
 *
 * @see paths["/users/{discordId}/timezone"]["put"]["requestBody"]["content"]["application/json"]
 */
export type users_discordId_timezone_put_Request = paths["/users/{discordId}/timezone"]["put"]["requestBody"]["content"]["application/json"];

/**
 * Request body for [PUT /users/{discordId}/defaultReminderTimeSpan]
 *
 * @see paths["/users/{discordId}/defaultReminderTimeSpan"]["put"]["requestBody"]["content"]["application/json"]
 */
export type users_discordId_defaultReminderTimeSpan_put_Request = paths["/users/{discordId}/defaultReminderTimeSpan"]["put"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /youtube 200]
 *
 * @see paths["/youtube"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type youtube_get_Response200 = paths["/youtube"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [POST /youtube]
 *
 * @see paths["/youtube"]["post"]["requestBody"]["content"]["application/json"]
 */
export type youtube_post_Request = paths["/youtube"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Request body for [PUT /youtube]
 *
 * @see paths["/youtube"]["put"]["requestBody"]["content"]["application/json"]
 */
export type youtube_put_Request = paths["/youtube"]["put"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /youtube/channel 200]
 *
 * @see paths["/youtube/channel"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type youtube_channel_get_Response200 = paths["/youtube/channel"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /youtube/{id} 200]
 *
 * @see paths["/youtube/{id}"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type youtube_id_get_Response200 = paths["/youtube/{id}"]["get"]["responses"]["200"]["content"]["application/json"];
