import type { paths } from "@zeffuro/fakegaming-common/api-types";

// ----- Autogenerated endpoint type aliases (types-only) -----

/**
 * Response for [POST /auth/login 200]
 *
 * @see paths["/auth/login"]["post"]["responses"]["200"]["content"]["application/json"]
 */
export type auth_login_post_Response200 = paths["/auth/login"]["post"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [POST /auth/login]
 *
 * @see paths["/auth/login"]["post"]["requestBody"]["content"]["application/json"]
 */
export type auth_login_post_Request = paths["/auth/login"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /birthdays 200]
 *
 * @see paths["/birthdays"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type birthdays_get_Response200 = paths["/birthdays"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [POST /birthdays]
 *
 * @see paths["/birthdays"]["post"]["requestBody"]["content"]["application/json"]
 */
export type birthdays_post_Request = paths["/birthdays"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /disabledCommands 200]
 *
 * @see paths["/disabledCommands"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type disabledCommands_get_Response200 = paths["/disabledCommands"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [POST /disabledCommands 201]
 *
 * @see paths["/disabledCommands"]["post"]["responses"]["201"]["content"]["application/json"]
 */
export type disabledCommands_post_Response201 = paths["/disabledCommands"]["post"]["responses"]["201"]["content"]["application/json"];

/**
 * Request body for [POST /disabledCommands]
 *
 * @see paths["/disabledCommands"]["post"]["requestBody"]["content"]["application/json"]
 */
export type disabledCommands_post_Request = paths["/disabledCommands"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /disabledCommands/check 200]
 *
 * @see paths["/disabledCommands/check"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type disabledCommands_check_get_Response200 = paths["/disabledCommands/check"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /disabledCommands/{id} 200]
 *
 * @see paths["/disabledCommands/{id}"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type disabledCommands_id_get_Response200 = paths["/disabledCommands/{id}"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [DELETE /disabledCommands/{id} 200]
 *
 * @see paths["/disabledCommands/{id}"]["delete"]["responses"]["200"]["content"]["application/json"]
 */
export type disabledCommands_id_delete_Response200 = paths["/disabledCommands/{id}"]["delete"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /disabledModules 200]
 *
 * @see paths["/disabledModules"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type disabledModules_get_Response200 = paths["/disabledModules"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [POST /disabledModules 201]
 *
 * @see paths["/disabledModules"]["post"]["responses"]["201"]["content"]["application/json"]
 */
export type disabledModules_post_Response201 = paths["/disabledModules"]["post"]["responses"]["201"]["content"]["application/json"];

/**
 * Request body for [POST /disabledModules]
 *
 * @see paths["/disabledModules"]["post"]["requestBody"]["content"]["application/json"]
 */
export type disabledModules_post_Request = paths["/disabledModules"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /disabledModules/check 200]
 *
 * @see paths["/disabledModules/check"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type disabledModules_check_get_Response200 = paths["/disabledModules/check"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /disabledModules/{id} 200]
 *
 * @see paths["/disabledModules/{id}"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type disabledModules_id_get_Response200 = paths["/disabledModules/{id}"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [DELETE /disabledModules/{id} 200]
 *
 * @see paths["/disabledModules/{id}"]["delete"]["responses"]["200"]["content"]["application/json"]
 */
export type disabledModules_id_delete_Response200 = paths["/disabledModules/{id}"]["delete"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [POST /discord/users/resolve 200]
 *
 * @see paths["/discord/users/resolve"]["post"]["responses"]["200"]["content"]["application/json"]
 */
export type discord_users_resolve_post_Response200 = paths["/discord/users/resolve"]["post"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [POST /discord/users/resolve]
 *
 * @see paths["/discord/users/resolve"]["post"]["requestBody"]["content"]["application/json"]
 */
export type discord_users_resolve_post_Request = paths["/discord/users/resolve"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /discord/guilds/{guildId}/members/search 200]
 *
 * @see paths["/discord/guilds/{guildId}/members/search"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type discord_guilds_guildId_members_search_get_Response200 = paths["/discord/guilds/{guildId}/members/search"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /patchNotes 200]
 *
 * @see paths["/patchNotes"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type patchNotes_get_Response200 = paths["/patchNotes"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [POST /patchNotes]
 *
 * @see paths["/patchNotes"]["post"]["requestBody"]["content"]["application/json"]
 */
export type patchNotes_post_Request = paths["/patchNotes"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /patchNotes/supportedGames 200]
 *
 * @see paths["/patchNotes/supportedGames"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type patchNotes_supportedGames_get_Response200 = paths["/patchNotes/supportedGames"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /patchNotes/{game} 200]
 *
 * @see paths["/patchNotes/{game}"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type patchNotes_game_get_Response200 = paths["/patchNotes/{game}"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [POST /patchSubscriptions]
 *
 * @see paths["/patchSubscriptions"]["post"]["requestBody"]["content"]["application/json"]
 */
export type patchSubscriptions_post_Request = paths["/patchSubscriptions"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Request body for [PUT /patchSubscriptions]
 *
 * @see paths["/patchSubscriptions"]["put"]["requestBody"]["content"]["application/json"]
 */
export type patchSubscriptions_put_Request = paths["/patchSubscriptions"]["put"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /quotes 200]
 *
 * @see paths["/quotes"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type quotes_get_Response200 = paths["/quotes"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [POST /quotes]
 *
 * @see paths["/quotes"]["post"]["requestBody"]["content"]["application/json"]
 */
export type quotes_post_Request = paths["/quotes"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /quotes/search 200]
 *
 * @see paths["/quotes/search"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type quotes_search_get_Response200 = paths["/quotes/search"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /quotes/guild/{guildId} 200]
 *
 * @see paths["/quotes/guild/{guildId}"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type quotes_guild_guildId_get_Response200 = paths["/quotes/guild/{guildId}"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /quotes/guild/{guildId}/author/{authorId} 200]
 *
 * @see paths["/quotes/guild/{guildId}/author/{authorId}"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type quotes_guild_guildId_author_authorId_get_Response200 = paths["/quotes/guild/{guildId}/author/{authorId}"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /reminders 200]
 *
 * @see paths["/reminders"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type reminders_get_Response200 = paths["/reminders"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [POST /reminders]
 *
 * @see paths["/reminders"]["post"]["requestBody"]["content"]["application/json"]
 */
export type reminders_post_Request = paths["/reminders"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /reminders/{id} 200]
 *
 * @see paths["/reminders/{id}"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type reminders_id_get_Response200 = paths["/reminders/{id}"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [POST /servers]
 *
 * @see paths["/servers"]["post"]["requestBody"]["content"]["application/json"]
 */
export type servers_post_Request = paths["/servers"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Request body for [PUT /servers/{serverId}]
 *
 * @see paths["/servers/{serverId}"]["put"]["requestBody"]["content"]["application/json"]
 */
export type servers_serverId_put_Request = paths["/servers/{serverId}"]["put"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /twitch 200]
 *
 * @see paths["/twitch"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type twitch_get_Response200 = paths["/twitch"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [POST /twitch 201]
 *
 * @see paths["/twitch"]["post"]["responses"]["201"]["content"]["application/json"]
 */
export type twitch_post_Response201 = paths["/twitch"]["post"]["responses"]["201"]["content"]["application/json"];

/**
 * Request body for [POST /twitch]
 *
 * @see paths["/twitch"]["post"]["requestBody"]["content"]["application/json"]
 */
export type twitch_post_Request = paths["/twitch"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /twitch/exists 200]
 *
 * @see paths["/twitch/exists"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type twitch_exists_get_Response200 = paths["/twitch/exists"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [GET /twitch/{id} 200]
 *
 * @see paths["/twitch/{id}"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type twitch_id_get_Response200 = paths["/twitch/{id}"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [PUT /twitch/{id} 200]
 *
 * @see paths["/twitch/{id}"]["put"]["responses"]["200"]["content"]["application/json"]
 */
export type twitch_id_put_Response200 = paths["/twitch/{id}"]["put"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [PUT /twitch/{id}]
 *
 * @see paths["/twitch/{id}"]["put"]["requestBody"]["content"]["application/json"]
 */
export type twitch_id_put_Request = paths["/twitch/{id}"]["put"]["requestBody"]["content"]["application/json"];

/**
 * Response for [DELETE /twitch/{id} 200]
 *
 * @see paths["/twitch/{id}"]["delete"]["responses"]["200"]["content"]["application/json"]
 */
export type twitch_id_delete_Response200 = paths["/twitch/{id}"]["delete"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [POST /users]
 *
 * @see paths["/users"]["post"]["requestBody"]["content"]["application/json"]
 */
export type users_post_Request = paths["/users"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Request body for [PUT /users/{discordId}]
 *
 * @see paths["/users/{discordId}"]["put"]["requestBody"]["content"]["application/json"]
 */
export type users_discordId_put_Request = paths["/users/{discordId}"]["put"]["requestBody"]["content"]["application/json"];

/**
 * Request body for [PUT /users/{discordId}/timezone]
 *
 * @see paths["/users/{discordId}/timezone"]["put"]["requestBody"]["content"]["application/json"]
 */
export type users_discordId_timezone_put_Request = paths["/users/{discordId}/timezone"]["put"]["requestBody"]["content"]["application/json"];

/**
 * Request body for [PUT /users/{discordId}/defaultReminderTimeSpan]
 *
 * @see paths["/users/{discordId}/defaultReminderTimeSpan"]["put"]["requestBody"]["content"]["application/json"]
 */
export type users_discordId_defaultReminderTimeSpan_put_Request = paths["/users/{discordId}/defaultReminderTimeSpan"]["put"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /youtube 200]
 *
 * @see paths["/youtube"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type youtube_get_Response200 = paths["/youtube"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [POST /youtube 201]
 *
 * @see paths["/youtube"]["post"]["responses"]["201"]["content"]["application/json"]
 */
export type youtube_post_Response201 = paths["/youtube"]["post"]["responses"]["201"]["content"]["application/json"];

/**
 * Request body for [POST /youtube]
 *
 * @see paths["/youtube"]["post"]["requestBody"]["content"]["application/json"]
 */
export type youtube_post_Request = paths["/youtube"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Response for [PUT /youtube 200]
 *
 * @see paths["/youtube"]["put"]["responses"]["200"]["content"]["application/json"]
 */
export type youtube_put_Response200 = paths["/youtube"]["put"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [PUT /youtube]
 *
 * @see paths["/youtube"]["put"]["requestBody"]["content"]["application/json"]
 */
export type youtube_put_Request = paths["/youtube"]["put"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /youtube/channel 200]
 *
 * @see paths["/youtube/channel"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type youtube_channel_get_Response200 = paths["/youtube/channel"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [POST /youtube/channel 201]
 *
 * @see paths["/youtube/channel"]["post"]["responses"]["201"]["content"]["application/json"]
 */
export type youtube_channel_post_Response201 = paths["/youtube/channel"]["post"]["responses"]["201"]["content"]["application/json"];

/**
 * Request body for [POST /youtube/channel]
 *
 * @see paths["/youtube/channel"]["post"]["requestBody"]["content"]["application/json"]
 */
export type youtube_channel_post_Request = paths["/youtube/channel"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Response for [GET /youtube/{id} 200]
 *
 * @see paths["/youtube/{id}"]["get"]["responses"]["200"]["content"]["application/json"]
 */
export type youtube_id_get_Response200 = paths["/youtube/{id}"]["get"]["responses"]["200"]["content"]["application/json"];

/**
 * Response for [PUT /youtube/{id} 200]
 *
 * @see paths["/youtube/{id}"]["put"]["responses"]["200"]["content"]["application/json"]
 */
export type youtube_id_put_Response200 = paths["/youtube/{id}"]["put"]["responses"]["200"]["content"]["application/json"];

/**
 * Request body for [PUT /youtube/{id}]
 *
 * @see paths["/youtube/{id}"]["put"]["requestBody"]["content"]["application/json"]
 */
export type youtube_id_put_Request = paths["/youtube/{id}"]["put"]["requestBody"]["content"]["application/json"];

/**
 * Response for [DELETE /youtube/{id} 200]
 *
 * @see paths["/youtube/{id}"]["delete"]["responses"]["200"]["content"]["application/json"]
 */
export type youtube_id_delete_Response200 = paths["/youtube/{id}"]["delete"]["responses"]["200"]["content"]["application/json"];
