import type { GameNightErrorCode } from '@zeffuro/fakegaming-common/managers';

export const gameNightCopy = {
    command: {
        start: 'Start a new game night in this channel',
        startName: 'A short name for this game night',
        duration: 'Hours before an unfinished game night expires',
        nominate: 'Nominate one game for the active game night',
        game: 'The game to nominate',
        open: 'Open voting on the nominations',
        close: 'Close voting and pick the winner',
        status: 'Show the current game night state',
    },
    guildOnly: 'Game Night Board is only available in a server.',
    created: 'Game Night Board created.',
    nominated: (game: string) => `Nominated **${game}**.`,
    votingOpened: 'Voting is open.',
    voteRecorded: (game: string) => `Your vote is now **${game}**.`,
    closed: 'The game night is finished.',
    unavailable: 'This game night is no longer available.',
    title: (name: string) => `**Game Night: ${name}**`,
    host: (creatorId: string) => `Host: <@${creatorId}>`,
    expiry: (unixSeconds: number) => `Expires: <t:${unixSeconds}:R>`,
    nominationHeading: 'Nominations',
    noNominations: 'No games have been nominated yet.',
    nominatingState: 'State: accepting nominations',
    votingState: 'State: voting is open',
    finishedState: 'State: finished',
    expiredState: 'State: expired without a selection',
    tonight: (game: string) => `Tonight: **${game}**`,
    tieResolved: (games: string) => `Tiebreak recorded between: ${games}.`,
    voteLine: (position: number, game: string, votes: number) => `${position}. **${game}** - ${votes} ${votes === 1 ? 'vote' : 'votes'}`,
    nominationLine: (position: number, game: string) => `${position}. **${game}**`,
    openVotingButton: 'Open voting',
    pickWinnerButton: 'Pick winner',
    error: (code: GameNightErrorCode): string => ({
        'active-session-exists': 'This server already has an active game night.',
        'duplicate-nomination': 'That game has already been nominated.',
        expired: 'This game night has expired.',
        'invalid-duration': 'Duration must be between 1 and 24 hours.',
        'invalid-name': 'Names must contain visible text and be no longer than 80 characters.',
        'nomination-limit': 'This game night already has five nominations.',
        'not-creator': 'Only the game night host can do that.',
        'not-found': 'There is no active game night here.',
        'not-nominating': 'This game night is no longer accepting nominations.',
        'not-voting': 'Voting is not open for this game night.',
        'own-nomination-exists': 'You have already nominated a game for this game night.',
        'too-few-nominations': 'At least two nominations are required before voting can open.',
        'wrong-channel': 'Use the channel containing the active Game Night Board.',
    })[code],
} as const;
