name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js, pnpm, and dependencies
        uses: ./.github/actions/setup-node-pnpm
        with:
          install-deps: 'true'
          build-natives: 'true'

      - name: Build all packages
        run: pnpm -r run build

      - name: Lint
        run: pnpm run lint

      - name: Run tests with coverage
        run: pnpm -r run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/api/lcov.info,./coverage/bot/lcov.info,./coverage/common/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
