name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Enable Corepack and install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: packages/dashboard/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Install dependencies (ignore scripts)
        run: pnpm install --ignore-scripts

      - name: Rebuild sqlite3 native bindings
        run: pnpm rebuild sqlite3

      - name: Build all packages
        run: pnpm -r run build

      - name: Lint
        run: pnpm run lint

      - name: Run tests
        run: pnpm test