name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: test-secret
      JWT_AUDIENCE: fakegaming-test
      JWT_ISSUER: fakegaming-ci
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js, pnpm, and dependencies
        uses: ./.github/actions/setup-node-pnpm
        with:
          install-deps: 'true'
          build-natives: 'true'

      - name: Assert JWT envs present (fail fast)
        run: pnpm run ci:assert-jwt

      - name: Check for env leaks (informational)
        run: pnpm run ci:check-env
        continue-on-error: true

      - name: Build all packages (orchestrated)
        run: pnpm run build

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck

      - name: Run tests with coverage
        run: pnpm -r run test:coverage

      - name: Check Codecov token present
        id: cc-token
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          if [ -z "${CODECOV_TOKEN}" ]; then
            echo "present=false" >> "$GITHUB_OUTPUT"
          else
            echo "present=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload coverage to Codecov
        if: steps.cc-token.outputs.present == 'true'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/api/lcov.info,./coverage/bot/lcov.info,./coverage/common/lcov.info,./coverage/dashboard/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

      - name: Codecov token missing (skipping upload)
        if: steps.cc-token.outputs.present != 'true'
        run: echo "CODECOV_TOKEN is not set; skipping coverage upload"
        continue-on-error: true

      - name: Duplication scan (informational)
        run: pnpm run scan:dupes
        continue-on-error: true
