name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js, pnpm, and dependencies
        uses: ./.github/actions/setup-node-pnpm
        with:
          install-deps: 'true'
          build-natives: 'true'

      - name: Build all packages
        run: pnpm -r run build

      - name: Lint
        run: pnpm run lint

      - name: Run tests
        run: pnpm test