name: Update Command Table

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/bot/src/modules/**/commands/*'
      - 'scripts/generate-command-table.ts'
      - '.github/workflows/update-command-table.yml'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-command-table:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Enable Corepack and install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build all packages
        run: pnpm -r run build

      - name: Generate README command table
        run: pnpm tsx scripts/generate-command-table.ts

      - name: Check for changes
        id: changes
        run: |
          if git diff --exit-code README.md; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create pull request for command table update
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: update command table in README [skip ci]"
          branch: "bot/update-command-table"
          title: "chore: update command table in README"
          body: "This PR updates the command table in the README automatically."
          labels: "bot, automated pr"
